--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Clickedtran/libRanks
build-by-default: true
branches:
- Master
projects:
  libRanks:
    path: ""
    model: virion
    type: library
...
